apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chef-service
  labels:
    io.kompose.service: ai-chef-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ai-chef-service
  template:
    metadata:
      labels:
        io.kompose.service: ai-chef-service
    spec:
      containers:
        - name: ai-chef-service
          image: mariem19/ai-chef-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-chef-secret
                  key: GEMINI_API_KEY
            - name: SPRING_PROFILES_ACTIVE
              value: docker
      restartPolicy: Always
