apiVersion: apps/v1
kind: Deployment
metadata:
  name: pantry-db
  labels:
    app: pantry-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pantry-db
  template:
    metadata:
      labels:
        app: pantry-db
    spec:
      containers:
        - name: pantry-db
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: pantrydb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
