apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service
  labels:
    io.kompose.service: recipe-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recipe-service
  template:
    metadata:
      labels:
        io.kompose.service: recipe-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z recipe-db 5432; do echo waiting for recipe-db; sleep 2; done;']
      containers:
        - name: recipe-service
          image: mariem19/recipe-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://recipe-db:5432/recipedb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          readinessProbe:
            exec:
              command: ["curl", "-f", "http://localhost:8083/actuator/health"]
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
      restartPolicy: Always
