name: Backend CI/CD

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, user-service, pantry-service, recipe-service, ai-chef-service]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3

    - name: Build and Test
      working-directory: ${{ matrix.service }}
      run: mvn clean test

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.service }}-jar
        path: ${{ matrix.service }}/target/*.jar

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    strategy:
      matrix:
        service: [api-gateway, user-service, pantry-service, recipe-service, ai-chef-service]
    
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.service }}-jar
        path: ${{ matrix.service }}/target

    - name: Build and Push Docker
      working-directory: ${{ matrix.service }}
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest