name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, user-service, pantry-service, recipe-service, ai-chef-service]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: temurin

    - name: Build ${{ matrix.service }}
      working-directory: ${{ matrix.service }}
      run: mvn clean install -B

    - name: Run Tests ${{ matrix.service }}
      working-directory: ${{ matrix.service }}
      run: mvn test

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: mariem19
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      working-directory: ${{ matrix.service }}
      run: |
        docker build -t mariem19/${{ matrix.service }}:latest .
        docker push mariem19/${{ matrix.service }}:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.30.0'

    - name: Configure kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Create GEMINI_API_KEY secret
      run: |
        kubectl create secret generic gemini-api-key \
          --from-literal=GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s-manifests/
